POST  http://localhost:9000/api/auth/register
Content-Type: application/json

{
    "username":"dawitsolo",
    "password":"12345678"
}

###

POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "username":"dawitsolo",
    "password":"12345678"
}

###

GET http://localhost:9000/api/auth/status


###

POST http://localhost:9000/api/auth/logout


### 
POST http://localhost:9000/api/auth/2fa/setup